Add validation to article creation screen.
pj-pss/community-supporter-app pull request #35
Opened 2018-02-02 07:25 UTC by tsukahara-t

* Check start date is before than end date.
   * If start date and end date is same, check to start time and end time.
* Check URL format.  (/^(https?|ftp)(:\/\/[-_.!~*\'()a-zA-Z0-9;\/?:\@&=+\$,%#]+)$/)
   * Check it start with "http://" or "https://" or "ftp://".
   * Check it use only half size alphabet and some symbols.
* Add error message.

closes #34

2018-02-04 11:46 UTC, dixonsiu requested changes

2018-02-04 11:46 UTC, dixonsiu commented on src/html/js/supporters.js
> +  if((startDate > endDate) || ((startDate == endDate) && (startTime > endTime))) {
Dateの比較はmoment.jsを使ってください。詳しいは[ここ](https://stackoverflow.com/questions/22600856/moment-js-date-time-comparison)。

2018-02-04 11:46 UTC, dixonsiu commented on src/html/js/supporters.js
> +  if(url && !url.match(/^(https?|ftp)(:\/\/[-_.!~*\'()a-zA-Z0-9;\/?:\@&=+\$,%#]+)$/)) {
URL のチェックなどは[parser](https://github.com/allmarkedup/purl)を使用してください。

2018-02-04 11:46 UTC, dixonsiu commented on src/html/js/supporters.js
> +  if((startDate > endDate) || ((startDate == endDate) && (startTime > endTime))) {
typeがeventでない場合もdateをチェックしまう。

2018-02-04 11:46 UTC, dixonsiu commented on src/html/js/supporters.js
> +  if( !(type && title && text) ||
switch statementを使う方が拡張しやすい。現在の処理はわかりにくい。

2018-02-04 11:46 UTC, dixonsiu commented on src/html/js/supporters.js
> +function varidateArticle() {
誤記：varidateArticle  
正しい：validateArticle

2018-02-05 05:31 UTC, dixonsiu approved these changes
時間がればswitch statmentのdefaultも使用してください。

2018-02-05 05:31 UTC, dixonsiu commented on src/html/js/supporters.js
> +  if(!(type && title && text)) {
typeがそれ以外の場合もswitch statementで制御できる。

2018-02-05 07:43 UTC, atsX approved these changes

2018-02-05 07:43 UTC, merged